---
# Ansible palybook projectPlaybook.yml
# ====================================
#
#   This is ansible playbook that triggers ansible roles for specified host
#   groups.

- hosts: global
  become: True          # Become root user when executing roles
  roles:
  - common

- hosts: webservers
  roles:
  - web

- hosts: loadbalancers
  become: True
  gather_facts: no      # Disable facts gathering as no facts are used here
  roles:
  - lba  

  tasks:
  - debug: msg="Hodnota"
